### ISSUE TITLE
Response poster tidak ada pada request https://berita-news.herokuapp.com/search/?q=

### ISSUE THREAD

**Issue by nuclearX** [rizki4106/API-BERITA-SINDO-NEWS#1]
Hallo, saya mencoba API yang anda buat dengan menggunakan fitur pencarian berita namun pada response yang didapat dari request [](https://berita-news.herokuapp.com/search/?q=) tidak menampilkan response poster. Apakah memang seperti itu apabila request menggunakan fitur pencarian?

**Comment by rizki4106** [comment]
Hallo..terimakasih telah melaporkan bug ini, akan saya perbaiki secepatnya, selagi saya membetulkan api ini mungkin ada baiknya untuk di pencariannya menggunakan api **cnn indonesia** yang saya buat ini [https://github.com/rizki4106/cnnindonesia-news-api](https://github.com/rizki4106/cnnindonesia-news-api)

**Comment by nuclearX** [comment]
Untuk yang cnn mungkin saya kurang suka di limit 7 result apabila menggunakan Pencarian Berita. 
BTW good job bro udah bikin API ginian.

**Comment by rizki4106** [comment]
API telah saya perbaiki dan sekarang poster sudah tersedia, silahkan di cek 🙌

**Comment by nuclearX** [comment]
> API telah saya perbaiki dan sekarang poster sudah tersedia, silahkan di cek 🙌

Mantap
