### ISSUE TITLE
Data 'Nasional' dan 'Internasional' Tidak ada

### ISSUE THREAD

**Issue by andes2912** [rizki4106/API-BERITA-SINDO-NEWS#2]
Mas, ini tadi baru coba, tapi untuk api yang nasional dan internasional data nya gak ada

**Comment by rizki4106** [comment]
Terimakasih sudah melaporkan kasus ini, akan saya perbaiki secepatnya, selagi menunggu saya sarankan untuk menggunakan api cnn indonesia berikut ini [https://github.com/rizki4106/cnnindonesia-news-api](https://github.com/rizki4106/cnnindonesia-news-api)

**Comment by andes2912** [comment]
Baik mas, thank u

**Comment by rizki4106** [comment]
hallo, bug sudah saya perbaiki sekarang berita internasional dan nasional sudah tersedia, Terimakasih

**Comment by andes2912** [comment]
Btw mas, API apa sudah Allow CORS ? soalnya saya coba aplikasikan dan sudah saya handle tetap saja tidak bisa.
Makasih
